#phpLDAPadmin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: osixia/phpldapadmin:0.9.0
        ports:
        - containerPort: 80
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: "openldap-service"
        - name: PHPLDAPADMIN_HTTPS
          value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin-service
  namespace: ldap
spec:
  selector:
    app: phpldapadmin
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort # 필요 시 LoadBalancer로 변경 가능